#!/usr/bin/env python
"""
gen_vbapi.py - generate the decompiler's VB-runtime ordinal table (vbNapi.txt)
directly from a msvbvmNN.dll export table.

The decompiler resolves a by-ordinal msvbvm import to a name+description via
data\vbNapi.txt (loaded by modNative.VBFunction_Description_Init). Each line is:

    <VA>,<ordinal>,<rtcName>,<description>

  - <ordinal>/<rtcName>  come straight from the DLL export table (authoritative,
    and correct PER VB VERSION: point at msvbvm50.dll for VB5, msvbvm60.dll for VB6).
  - <VA>                 is informational only (the decompiler looks up by ORDINAL),
    emitted as RVA + the DLL's ImageBase to match the original convention.
  - <description>        is the readable VB function the call renders as ("Chr()",
    "Mid()", ...) or "undef" for an internal helper with no VB-source equivalent.
    The rtc NAMES are stable across VB5/VB6, so a single rtcName->description map
    seeds every version's file. We seed it from the existing vbNapi.txt files so all
    current curation is preserved, then layer ADD_DESC on top.

CRITICAL: the file MUST be written with CRLF line endings + a trailing "EOF" line.
VB6 `Input #` uses CR/CRLF as the record separator; an LF-only file is read as one
giant record and the loader dies with "Type mismatch" in frmMain_Load.

Usage:
    python gen_vbapi.py <msvbvmNN.dll> <out\\vbNapi.txt> [seed1.txt seed2.txt ...]
Example (run from the project root):
    python tools\\gen_vbapi.py C:\\Windows\\SysWOW64\\msvbvm60.dll "Install Folder\\data\\vb6api.txt" "data\\vb6api.txt"
"""
import sys, os, pefile

# rtcName -> description fixes/additions layered on top of the seeded map.
# (rtc names are identical in msvbvm50 and msvbvm60, so this serves both.)
ADD_DESC = {
    "rtcVarBstrFromAnsi": "Chr()",      # ord608 - was "undef"
    "rtcVarFromFormatVar": "Format()",  # ord660 - was "undef"
}


def load_desc(seed_paths):
    """rtcName -> description, from existing vbNapi.txt seed files (CRLF or LF tolerant)."""
    desc = {}
    for p in seed_paths:
        try:
            with open(p, "r", errors="replace") as f:
                for ln in f:
                    parts = ln.rstrip("\r\n").split(",")
                    if len(parts) >= 4 and parts[1].strip().isdigit():
                        name, d = parts[2].strip(), parts[3]
                        if d and d != "undef" and name:
                            desc[name] = d
        except OSError:
            pass
    desc.update(ADD_DESC)
    return desc


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(2)
    dll, out = sys.argv[1], sys.argv[2]
    seeds = sys.argv[3:]
    if not os.path.isfile(dll):
        print("ERROR: DLL not found: %s" % dll)
        print("  (VB5's msvbvm50.dll is not installed by default on modern Windows -")
        print("   copy it from a VB5 install or the redistributable, then re-run.)")
        sys.exit(1)
    desc = load_desc(seeds)

    pe = pefile.PE(dll)
    ib = pe.OPTIONAL_HEADER.ImageBase
    exports = []
    for e in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if e.name:                                  # named export (skip pure-ordinal/forwarders)
            exports.append((e.ordinal, e.name.decode(), e.address + ib))
    exports.sort(key=lambda t: t[0])

    named = sum(1 for _, n, _ in exports if desc.get(n, "undef") != "undef")
    lines = ["%08X,%d,%s,%s" % (va, o, n, desc.get(n, "undef")) for (o, n, va) in exports]
    # Terminator: the loader (VBFunction_Description_Init) does
    #   Input #f, sAdr, sOrd, sName, sDef  ' reads 4 fields per record
    #   If LCase$(sAdr) <> "eof" Then ... Else Exit Do
    # so the EOF record must supply all 4 fields ON ITS OWN LINE (a bare "EOF"
    # makes Input # read the next lines for sOrd/sName/sDef and hit
    # "Input past end of file").  Extra trailer lines are belt-and-suspenders.
    lines.append("EOF,0,EOF,EOF")
    lines.append("List generated by gen_vbapi.py from " + dll)
    lines.append("(end)")
    lines.append("(end)")

    # CRLF, binary write (no text-mode newline translation).
    with open(out, "wb") as f:
        f.write(("\r\n".join(lines) + "\r\n").encode("latin-1", "replace"))

    print("wrote %s: %d ordinals, %d with a VB-function description" % (out, len(exports), named))


if __name__ == "__main__":
    main()
